package com.konfigthis.client;

import com.konfigthis.client.api.AuthorizationApi;
import com.konfigthis.client.api.ClassificationsApi;
import com.konfigthis.client.api.ClassificationsOnFilesApi;
import com.konfigthis.client.api.ClassificationsOnFoldersApi;
import com.konfigthis.client.api.CollaborationsApi;
import com.konfigthis.client.api.CollaborationsListApi;
import com.konfigthis.client.api.CollectionsApi;
import com.konfigthis.client.api.CommentsApi;
import com.konfigthis.client.api.DevicePinnersApi;
import com.konfigthis.client.api.DomainRestrictionsUserExemptionsApi;
import com.konfigthis.client.api.DomainRestrictionsForCollaborationsApi;
import com.konfigthis.client.api.DownloadsApi;
import com.konfigthis.client.api.EmailAliasesApi;
import com.konfigthis.client.api.EventsApi;
import com.konfigthis.client.api.FileRequestsApi;
import com.konfigthis.client.api.FileVersionLegalHoldsApi;
import com.konfigthis.client.api.FileVersionRetentionsApi;
import com.konfigthis.client.api.FileVersionsApi;
import com.konfigthis.client.api.FilesApi;
import com.konfigthis.client.api.FolderLocksApi;
import com.konfigthis.client.api.FoldersApi;
import com.konfigthis.client.api.GroupMembershipsApi;
import com.konfigthis.client.api.GroupsApi;
import com.konfigthis.client.api.IntegrationMappingsApi;
import com.konfigthis.client.api.InvitesApi;
import com.konfigthis.client.api.LegalHoldPoliciesApi;
import com.konfigthis.client.api.LegalHoldPolicyAssignmentsApi;
import com.konfigthis.client.api.MetadataCascadePoliciesApi;
import com.konfigthis.client.api.MetadataInstancesFilesApi;
import com.konfigthis.client.api.MetadataInstancesFoldersApi;
import com.konfigthis.client.api.MetadataTemplatesApi;
import com.konfigthis.client.api.RecentItemsApi;
import com.konfigthis.client.api.RetentionPoliciesApi;
import com.konfigthis.client.api.RetentionPolicyAssignmentsApi;
import com.konfigthis.client.api.SearchApi;
import com.konfigthis.client.api.SessionTerminationApi;
import com.konfigthis.client.api.SharedLinksFilesApi;
import com.konfigthis.client.api.SharedLinksFoldersApi;
import com.konfigthis.client.api.SharedLinksWebLinksApi;
import com.konfigthis.client.api.ShieldInformationBarrierReportsApi;
import com.konfigthis.client.api.ShieldInformationBarrierSegmentMembersApi;
import com.konfigthis.client.api.ShieldInformationBarrierSegmentRestrictionsApi;
import com.konfigthis.client.api.ShieldInformationBarrierSegmentsApi;
import com.konfigthis.client.api.ShieldInformationBarriersApi;
import com.konfigthis.client.api.SignRequestsApi;
import com.konfigthis.client.api.SignTemplatesApi;
import com.konfigthis.client.api.SkillsApi;
import com.konfigthis.client.api.StandardAndZonesStoragePoliciesApi;
import com.konfigthis.client.api.StandardAndZonesStoragePolicyAssignmentsApi;
import com.konfigthis.client.api.TaskAssignmentsApi;
import com.konfigthis.client.api.TasksApi;
import com.konfigthis.client.api.TermsOfServiceApi;
import com.konfigthis.client.api.TermsOfServiceUserStatusesApi;
import com.konfigthis.client.api.TransferFoldersApi;
import com.konfigthis.client.api.TrashedFilesApi;
import com.konfigthis.client.api.TrashedFoldersApi;
import com.konfigthis.client.api.TrashedItemsApi;
import com.konfigthis.client.api.TrashedWebLinksApi;
import com.konfigthis.client.api.UploadsApi;
import com.konfigthis.client.api.UploadsChunkedApi;
import com.konfigthis.client.api.UserAvatarsApi;
import com.konfigthis.client.api.UsersApi;
import com.konfigthis.client.api.WatermarksFilesApi;
import com.konfigthis.client.api.WatermarksFoldersApi;
import com.konfigthis.client.api.WebLinksApi;
import com.konfigthis.client.api.WebhooksApi;
import com.konfigthis.client.api.WorkflowsApi;
import com.konfigthis.client.api.ZipDownloadsApi;

public class Box {
    private ApiClient apiClient;
    public final AuthorizationApi authorization;
    public final ClassificationsApi classifications;
    public final ClassificationsOnFilesApi classificationsOnFiles;
    public final ClassificationsOnFoldersApi classificationsOnFolders;
    public final CollaborationsApi collaborations;
    public final CollaborationsListApi collaborationsList;
    public final CollectionsApi collections;
    public final CommentsApi comments;
    public final DevicePinnersApi devicePinners;
    public final DomainRestrictionsUserExemptionsApi domainRestrictionsUserExemptions;
    public final DomainRestrictionsForCollaborationsApi domainRestrictionsForCollaborations;
    public final DownloadsApi downloads;
    public final EmailAliasesApi emailAliases;
    public final EventsApi events;
    public final FileRequestsApi fileRequests;
    public final FileVersionLegalHoldsApi fileVersionLegalHolds;
    public final FileVersionRetentionsApi fileVersionRetentions;
    public final FileVersionsApi fileVersions;
    public final FilesApi files;
    public final FolderLocksApi folderLocks;
    public final FoldersApi folders;
    public final GroupMembershipsApi groupMemberships;
    public final GroupsApi groups;
    public final IntegrationMappingsApi integrationMappings;
    public final InvitesApi invites;
    public final LegalHoldPoliciesApi legalHoldPolicies;
    public final LegalHoldPolicyAssignmentsApi legalHoldPolicyAssignments;
    public final MetadataCascadePoliciesApi metadataCascadePolicies;
    public final MetadataInstancesFilesApi metadataInstancesFiles;
    public final MetadataInstancesFoldersApi metadataInstancesFolders;
    public final MetadataTemplatesApi metadataTemplates;
    public final RecentItemsApi recentItems;
    public final RetentionPoliciesApi retentionPolicies;
    public final RetentionPolicyAssignmentsApi retentionPolicyAssignments;
    public final SearchApi search;
    public final SessionTerminationApi sessionTermination;
    public final SharedLinksFilesApi sharedLinksFiles;
    public final SharedLinksFoldersApi sharedLinksFolders;
    public final SharedLinksWebLinksApi sharedLinksWebLinks;
    public final ShieldInformationBarrierReportsApi shieldInformationBarrierReports;
    public final ShieldInformationBarrierSegmentMembersApi shieldInformationBarrierSegmentMembers;
    public final ShieldInformationBarrierSegmentRestrictionsApi shieldInformationBarrierSegmentRestrictions;
    public final ShieldInformationBarrierSegmentsApi shieldInformationBarrierSegments;
    public final ShieldInformationBarriersApi shieldInformationBarriers;
    public final SignRequestsApi signRequests;
    public final SignTemplatesApi signTemplates;
    public final SkillsApi skills;
    public final StandardAndZonesStoragePoliciesApi standardAndZonesStoragePolicies;
    public final StandardAndZonesStoragePolicyAssignmentsApi standardAndZonesStoragePolicyAssignments;
    public final TaskAssignmentsApi taskAssignments;
    public final TasksApi tasks;
    public final TermsOfServiceApi termsOfService;
    public final TermsOfServiceUserStatusesApi termsOfServiceUserStatuses;
    public final TransferFoldersApi transferFolders;
    public final TrashedFilesApi trashedFiles;
    public final TrashedFoldersApi trashedFolders;
    public final TrashedItemsApi trashedItems;
    public final TrashedWebLinksApi trashedWebLinks;
    public final UploadsApi uploads;
    public final UploadsChunkedApi uploadsChunked;
    public final UserAvatarsApi userAvatars;
    public final UsersApi users;
    public final WatermarksFilesApi watermarksFiles;
    public final WatermarksFoldersApi watermarksFolders;
    public final WebLinksApi webLinks;
    public final WebhooksApi webhooks;
    public final WorkflowsApi workflows;
    public final ZipDownloadsApi zipDownloads;

    public Box() {
        this(null);
    }

    public Box(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.authorization = new AuthorizationApi(this.apiClient);
        this.classifications = new ClassificationsApi(this.apiClient);
        this.classificationsOnFiles = new ClassificationsOnFilesApi(this.apiClient);
        this.classificationsOnFolders = new ClassificationsOnFoldersApi(this.apiClient);
        this.collaborations = new CollaborationsApi(this.apiClient);
        this.collaborationsList = new CollaborationsListApi(this.apiClient);
        this.collections = new CollectionsApi(this.apiClient);
        this.comments = new CommentsApi(this.apiClient);
        this.devicePinners = new DevicePinnersApi(this.apiClient);
        this.domainRestrictionsUserExemptions = new DomainRestrictionsUserExemptionsApi(this.apiClient);
        this.domainRestrictionsForCollaborations = new DomainRestrictionsForCollaborationsApi(this.apiClient);
        this.downloads = new DownloadsApi(this.apiClient);
        this.emailAliases = new EmailAliasesApi(this.apiClient);
        this.events = new EventsApi(this.apiClient);
        this.fileRequests = new FileRequestsApi(this.apiClient);
        this.fileVersionLegalHolds = new FileVersionLegalHoldsApi(this.apiClient);
        this.fileVersionRetentions = new FileVersionRetentionsApi(this.apiClient);
        this.fileVersions = new FileVersionsApi(this.apiClient);
        this.files = new FilesApi(this.apiClient);
        this.folderLocks = new FolderLocksApi(this.apiClient);
        this.folders = new FoldersApi(this.apiClient);
        this.groupMemberships = new GroupMembershipsApi(this.apiClient);
        this.groups = new GroupsApi(this.apiClient);
        this.integrationMappings = new IntegrationMappingsApi(this.apiClient);
        this.invites = new InvitesApi(this.apiClient);
        this.legalHoldPolicies = new LegalHoldPoliciesApi(this.apiClient);
        this.legalHoldPolicyAssignments = new LegalHoldPolicyAssignmentsApi(this.apiClient);
        this.metadataCascadePolicies = new MetadataCascadePoliciesApi(this.apiClient);
        this.metadataInstancesFiles = new MetadataInstancesFilesApi(this.apiClient);
        this.metadataInstancesFolders = new MetadataInstancesFoldersApi(this.apiClient);
        this.metadataTemplates = new MetadataTemplatesApi(this.apiClient);
        this.recentItems = new RecentItemsApi(this.apiClient);
        this.retentionPolicies = new RetentionPoliciesApi(this.apiClient);
        this.retentionPolicyAssignments = new RetentionPolicyAssignmentsApi(this.apiClient);
        this.search = new SearchApi(this.apiClient);
        this.sessionTermination = new SessionTerminationApi(this.apiClient);
        this.sharedLinksFiles = new SharedLinksFilesApi(this.apiClient);
        this.sharedLinksFolders = new SharedLinksFoldersApi(this.apiClient);
        this.sharedLinksWebLinks = new SharedLinksWebLinksApi(this.apiClient);
        this.shieldInformationBarrierReports = new ShieldInformationBarrierReportsApi(this.apiClient);
        this.shieldInformationBarrierSegmentMembers = new ShieldInformationBarrierSegmentMembersApi(this.apiClient);
        this.shieldInformationBarrierSegmentRestrictions = new ShieldInformationBarrierSegmentRestrictionsApi(this.apiClient);
        this.shieldInformationBarrierSegments = new ShieldInformationBarrierSegmentsApi(this.apiClient);
        this.shieldInformationBarriers = new ShieldInformationBarriersApi(this.apiClient);
        this.signRequests = new SignRequestsApi(this.apiClient);
        this.signTemplates = new SignTemplatesApi(this.apiClient);
        this.skills = new SkillsApi(this.apiClient);
        this.standardAndZonesStoragePolicies = new StandardAndZonesStoragePoliciesApi(this.apiClient);
        this.standardAndZonesStoragePolicyAssignments = new StandardAndZonesStoragePolicyAssignmentsApi(this.apiClient);
        this.taskAssignments = new TaskAssignmentsApi(this.apiClient);
        this.tasks = new TasksApi(this.apiClient);
        this.termsOfService = new TermsOfServiceApi(this.apiClient);
        this.termsOfServiceUserStatuses = new TermsOfServiceUserStatusesApi(this.apiClient);
        this.transferFolders = new TransferFoldersApi(this.apiClient);
        this.trashedFiles = new TrashedFilesApi(this.apiClient);
        this.trashedFolders = new TrashedFoldersApi(this.apiClient);
        this.trashedItems = new TrashedItemsApi(this.apiClient);
        this.trashedWebLinks = new TrashedWebLinksApi(this.apiClient);
        this.uploads = new UploadsApi(this.apiClient);
        this.uploadsChunked = new UploadsChunkedApi(this.apiClient);
        this.userAvatars = new UserAvatarsApi(this.apiClient);
        this.users = new UsersApi(this.apiClient);
        this.watermarksFiles = new WatermarksFilesApi(this.apiClient);
        this.watermarksFolders = new WatermarksFoldersApi(this.apiClient);
        this.webLinks = new WebLinksApi(this.apiClient);
        this.webhooks = new WebhooksApi(this.apiClient);
        this.workflows = new WorkflowsApi(this.apiClient);
        this.zipDownloads = new ZipDownloadsApi(this.apiClient);
    }

}
