/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Annotation;
import com.konfigthis.client.model.AppActivity;
import com.konfigthis.client.model.FaCommentFull;
import com.konfigthis.client.model.TaskFull;
import com.konfigthis.client.model.VersionsActivity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ActivitySource
 */
public class ActivitySourceTest {
    private final ActivitySource model = new ActivitySource();

    /**
     * Model tests for ActivitySource
     */
    @Test
    public void testActivitySource() {
        // TODO: test ActivitySource
    }

    /**
     * Test the property 'annotation'
     */
    @Test
    public void annotationTest() {
        // TODO: test annotation
    }

    /**
     * Test the property 'appActivity'
     */
    @Test
    public void appActivityTest() {
        // TODO: test appActivity
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'versions'
     */
    @Test
    public void versionsTest() {
        // TODO: test versions
    }

}
