/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClassificationsUpdateLabelsDescriptionsRequestInnerData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ClassificationsUpdateLabelsDescriptionsRequestInner
 */
public class ClassificationsUpdateLabelsDescriptionsRequestInnerTest {
    private final ClassificationsUpdateLabelsDescriptionsRequestInner model = new ClassificationsUpdateLabelsDescriptionsRequestInner();

    /**
     * Model tests for ClassificationsUpdateLabelsDescriptionsRequestInner
     */
    @Test
    public void testClassificationsUpdateLabelsDescriptionsRequestInner() {
        // TODO: test ClassificationsUpdateLabelsDescriptionsRequestInner
    }

    /**
     * Test the property 'op'
     */
    @Test
    public void opTest() {
        // TODO: test op
    }

    /**
     * Test the property 'fieldKey'
     */
    @Test
    public void fieldKeyTest() {
        // TODO: test fieldKey
    }

    /**
     * Test the property 'enumOptionKey'
     */
    @Test
    public void enumOptionKeyTest() {
        // TODO: test enumOptionKey
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
