/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TrackingCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostUsersRequest
 */
public class PostUsersRequestTest {
    private final PostUsersRequest model = new PostUsersRequest();

    /**
     * Model tests for PostUsersRequest
     */
    @Test
    public void testPostUsersRequest() {
        // TODO: test PostUsersRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'login'
     */
    @Test
    public void loginTest() {
        // TODO: test login
    }

    /**
     * Test the property 'isPlatformAccessOnly'
     */
    @Test
    public void isPlatformAccessOnlyTest() {
        // TODO: test isPlatformAccessOnly
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'isSyncEnabled'
     */
    @Test
    public void isSyncEnabledTest() {
        // TODO: test isSyncEnabled
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'spaceAmount'
     */
    @Test
    public void spaceAmountTest() {
        // TODO: test spaceAmount
    }

    /**
     * Test the property 'trackingCodes'
     */
    @Test
    public void trackingCodesTest() {
        // TODO: test trackingCodes
    }

    /**
     * Test the property 'canSeeManagedUsers'
     */
    @Test
    public void canSeeManagedUsersTest() {
        // TODO: test canSeeManagedUsers
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'isExternalCollabRestricted'
     */
    @Test
    public void isExternalCollabRestrictedTest() {
        // TODO: test isExternalCollabRestricted
    }

    /**
     * Test the property 'isExemptFromDeviceLimits'
     */
    @Test
    public void isExemptFromDeviceLimitsTest() {
        // TODO: test isExemptFromDeviceLimits
    }

    /**
     * Test the property 'isExemptFromLoginVerification'
     */
    @Test
    public void isExemptFromLoginVerificationTest() {
        // TODO: test isExemptFromLoginVerification
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'externalAppUserId'
     */
    @Test
    public void externalAppUserIdTest() {
        // TODO: test externalAppUserId
    }

}
