/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RetentionPolicyMiniAllOf
 */
public class RetentionPolicyMiniAllOfTest {
    private final RetentionPolicyMiniAllOf model = new RetentionPolicyMiniAllOf();

    /**
     * Model tests for RetentionPolicyMiniAllOf
     */
    @Test
    public void testRetentionPolicyMiniAllOf() {
        // TODO: test RetentionPolicyMiniAllOf
    }

    /**
     * Test the property 'policyName'
     */
    @Test
    public void policyNameTest() {
        // TODO: test policyName
    }

    /**
     * Test the property 'retentionLength'
     */
    @Test
    public void retentionLengthTest() {
        // TODO: test retentionLength
    }

    /**
     * Test the property 'dispositionAction'
     */
    @Test
    public void dispositionActionTest() {
        // TODO: test dispositionAction
    }

}
