/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.StatusSkillCardInvocation;
import com.konfigthis.client.model.StatusSkillCardSkill;
import com.konfigthis.client.model.StatusSkillCardSkillCardTitle;
import com.konfigthis.client.model.StatusSkillCardStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StatusSkillCard
 */
public class StatusSkillCardTest {
    private final StatusSkillCard model = new StatusSkillCard();

    /**
     * Model tests for StatusSkillCard
     */
    @Test
    public void testStatusSkillCard() {
        // TODO: test StatusSkillCard
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'skillCardType'
     */
    @Test
    public void skillCardTypeTest() {
        // TODO: test skillCardType
    }

    /**
     * Test the property 'skillCardTitle'
     */
    @Test
    public void skillCardTitleTest() {
        // TODO: test skillCardTitle
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'skill'
     */
    @Test
    public void skillTest() {
        // TODO: test skill
    }

    /**
     * Test the property 'invocation'
     */
    @Test
    public void invocationTest() {
        // TODO: test invocation
    }

}
