/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CollaboratorVariableVariableValueInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A collaborator object. Allows to specify a list of user ID&#39;s that are affected by the workflow result.
 */
@ApiModel(description = "A collaborator object. Allows to specify a list of user ID's that are affected by the workflow result.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CollaboratorVariable {
  /**
   * Collaborator object type. 
   */
  @JsonAdapter(TypeEnum.Adapter.class)
 public enum TypeEnum {
    VARIABLE("variable");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  /**
   * Variable type  for the Collaborator object. 
   */
  @JsonAdapter(VariableTypeEnum.Adapter.class)
 public enum VariableTypeEnum {
    USER_LIST("user_list");

    private String value;

    VariableTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static VariableTypeEnum fromValue(String value) {
      for (VariableTypeEnum b : VariableTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<VariableTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final VariableTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public VariableTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return VariableTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_VARIABLE_TYPE = "variable_type";
  @SerializedName(SERIALIZED_NAME_VARIABLE_TYPE)
  private VariableTypeEnum variableType;

  public static final String SERIALIZED_NAME_VARIABLE_VALUE = "variable_value";
  @SerializedName(SERIALIZED_NAME_VARIABLE_VALUE)
  private List<CollaboratorVariableVariableValueInner> variableValue = new ArrayList<>();

  public CollaboratorVariable() {
  }

  public CollaboratorVariable type(TypeEnum type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Collaborator object type. 
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "VARIABLE", required = true, value = "Collaborator object type. ")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    
    
    
    this.type = type;
  }


  public CollaboratorVariable variableType(VariableTypeEnum variableType) {
    
    
    
    
    this.variableType = variableType;
    return this;
  }

   /**
   * Variable type  for the Collaborator object. 
   * @return variableType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "USER_LIST", required = true, value = "Variable type  for the Collaborator object. ")

  public VariableTypeEnum getVariableType() {
    return variableType;
  }


  public void setVariableType(VariableTypeEnum variableType) {
    
    
    
    this.variableType = variableType;
  }


  public CollaboratorVariable variableValue(List<CollaboratorVariableVariableValueInner> variableValue) {
    
    
    
    
    this.variableValue = variableValue;
    return this;
  }

  public CollaboratorVariable addVariableValueItem(CollaboratorVariableVariableValueInner variableValueItem) {
    this.variableValue.add(variableValueItem);
    return this;
  }

   /**
   * A list of user IDs.
   * @return variableValue
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of user IDs.")

  public List<CollaboratorVariableVariableValueInner> getVariableValue() {
    return variableValue;
  }


  public void setVariableValue(List<CollaboratorVariableVariableValueInner> variableValue) {
    
    
    
    this.variableValue = variableValue;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CollaboratorVariable instance itself
   */
  public CollaboratorVariable putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollaboratorVariable collaboratorVariable = (CollaboratorVariable) o;
    return Objects.equals(this.type, collaboratorVariable.type) &&
        Objects.equals(this.variableType, collaboratorVariable.variableType) &&
        Objects.equals(this.variableValue, collaboratorVariable.variableValue)&&
        Objects.equals(this.additionalProperties, collaboratorVariable.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, variableType, variableValue, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollaboratorVariable {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    variableType: ").append(toIndentedString(variableType)).append("\n");
    sb.append("    variableValue: ").append(toIndentedString(variableValue)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("variable_type");
    openapiFields.add("variable_value");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("variable_type");
    openapiRequiredFields.add("variable_value");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CollaboratorVariable
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CollaboratorVariable.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CollaboratorVariable is not found in the empty JSON string", CollaboratorVariable.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CollaboratorVariable.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if (!jsonObj.get("variable_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `variable_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("variable_type").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("variable_value").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `variable_value` to be an array in the JSON string but got `%s`", jsonObj.get("variable_value").toString()));
      }

      JsonArray jsonArrayvariableValue = jsonObj.getAsJsonArray("variable_value");
      // validate the required field `variable_value` (array)
      for (int i = 0; i < jsonArrayvariableValue.size(); i++) {
        CollaboratorVariableVariableValueInner.validateJsonObject(jsonArrayvariableValue.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CollaboratorVariable.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CollaboratorVariable' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CollaboratorVariable> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CollaboratorVariable.class));

       return (TypeAdapter<T>) new TypeAdapter<CollaboratorVariable>() {
           @Override
           public void write(JsonWriter out, CollaboratorVariable value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CollaboratorVariable read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CollaboratorVariable instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CollaboratorVariable given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CollaboratorVariable
  * @throws IOException if the JSON string is invalid with respect to CollaboratorVariable
  */
  public static CollaboratorVariable fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CollaboratorVariable.class);
  }

 /**
  * Convert an instance of CollaboratorVariable to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

