/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TemplateSignerInputAllOfCoordinates;
import com.konfigthis.client.model.TemplateSignerInputAllOfDimensions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TemplateSignerInputAllOf
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TemplateSignerInputAllOf {
  /**
   * Type of input
   */
  @JsonAdapter(TypeEnum.Adapter.class)
 public enum TypeEnum {
    SIGNATURE("signature"),
    
    DATE("date"),
    
    TEXT("text"),
    
    CHECKBOX("checkbox"),
    
    ATTACHMENT("attachment"),
    
    RADIO("radio"),
    
    DROPDOWN("dropdown");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  /**
   * Content type of input
   */
  @JsonAdapter(ContentTypeEnum.Adapter.class)
 public enum ContentTypeEnum {
    SIGNATURE("signature"),
    
    INITIAL("initial"),
    
    STAMP("stamp"),
    
    DATE("date"),
    
    CHECKBOX("checkbox"),
    
    TEXT("text"),
    
    FULL_NAME("full_name"),
    
    FIRST_NAME("first_name"),
    
    LAST_NAME("last_name"),
    
    COMPANY("company"),
    
    TITLE("title"),
    
    EMAIL("email"),
    
    ATTACHMENT("attachment"),
    
    RADIO("radio"),
    
    DROPDOWN("dropdown");

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ContentTypeEnum fromValue(String value) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ContentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ContentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ContentTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "content_type";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  private ContentTypeEnum contentType;

  public static final String SERIALIZED_NAME_IS_REQUIRED = "is_required";
  @SerializedName(SERIALIZED_NAME_IS_REQUIRED)
  private Boolean isRequired;

  public static final String SERIALIZED_NAME_PAGE_INDEX = "page_index";
  @SerializedName(SERIALIZED_NAME_PAGE_INDEX)
  private Integer pageIndex;

  public static final String SERIALIZED_NAME_DOCUMENT_ID = "document_id";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_ID)
  private String documentId;

  public static final String SERIALIZED_NAME_DROPDOWN_CHOICES = "dropdown_choices";
  @SerializedName(SERIALIZED_NAME_DROPDOWN_CHOICES)
  private List<String> dropdownChoices = null;

  public static final String SERIALIZED_NAME_GROUP_ID = "group_id";
  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  private String groupId;

  public static final String SERIALIZED_NAME_COORDINATES = "coordinates";
  @SerializedName(SERIALIZED_NAME_COORDINATES)
  private TemplateSignerInputAllOfCoordinates coordinates;

  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  private TemplateSignerInputAllOfDimensions dimensions;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_READ_ONLY = "read_only";
  @SerializedName(SERIALIZED_NAME_READ_ONLY)
  private Boolean readOnly;

  public TemplateSignerInputAllOf() {
  }

  public TemplateSignerInputAllOf type(TypeEnum type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Type of input
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "TEXT", value = "Type of input")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    
    
    
    this.type = type;
  }


  public TemplateSignerInputAllOf contentType(ContentTypeEnum contentType) {
    
    
    
    
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of input
   * @return contentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "TEXT", value = "Content type of input")

  public ContentTypeEnum getContentType() {
    return contentType;
  }


  public void setContentType(ContentTypeEnum contentType) {
    
    
    
    this.contentType = contentType;
  }


  public TemplateSignerInputAllOf isRequired(Boolean isRequired) {
    
    
    
    
    this.isRequired = isRequired;
    return this;
  }

   /**
   * Whether or not the input is required.
   * @return isRequired
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Whether or not the input is required.")

  public Boolean getIsRequired() {
    return isRequired;
  }


  public void setIsRequired(Boolean isRequired) {
    
    
    
    this.isRequired = isRequired;
  }


  public TemplateSignerInputAllOf pageIndex(Integer pageIndex) {
    
    
    
    
    this.pageIndex = pageIndex;
    return this;
  }

   /**
   * Index of page that the input is on.
   * @return pageIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "4", value = "Index of page that the input is on.")

  public Integer getPageIndex() {
    return pageIndex;
  }


  public void setPageIndex(Integer pageIndex) {
    
    
    
    this.pageIndex = pageIndex;
  }


  public TemplateSignerInputAllOf documentId(String documentId) {
    
    
    
    
    this.documentId = documentId;
    return this;
  }

   /**
   * Document identifier.
   * @return documentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123075213-eb54b537-8b25-445e-87c1-5a1c67d8cbd7", value = "Document identifier.")

  public String getDocumentId() {
    return documentId;
  }


  public void setDocumentId(String documentId) {
    
    
    
    this.documentId = documentId;
  }


  public TemplateSignerInputAllOf dropdownChoices(List<String> dropdownChoices) {
    
    
    
    
    this.dropdownChoices = dropdownChoices;
    return this;
  }

  public TemplateSignerInputAllOf addDropdownChoicesItem(String dropdownChoicesItem) {
    if (this.dropdownChoices == null) {
      this.dropdownChoices = new ArrayList<>();
    }
    this.dropdownChoices.add(dropdownChoicesItem);
    return this;
  }

   /**
   * When the input is of the type &#x60;dropdown&#x60; this values will be filled with all the dropdown options.
   * @return dropdownChoices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[true,false,\"Maybe\"]", value = "When the input is of the type `dropdown` this values will be filled with all the dropdown options.")

  public List<String> getDropdownChoices() {
    return dropdownChoices;
  }


  public void setDropdownChoices(List<String> dropdownChoices) {
    
    
    
    this.dropdownChoices = dropdownChoices;
  }


  public TemplateSignerInputAllOf groupId(String groupId) {
    
    
    
    
    this.groupId = groupId;
    return this;
  }

   /**
   * When the input is of type &#x60;radio&#x60; they can be grouped to gather with this identifier.
   * @return groupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "da317330-225a-4c72-89ad-0d6dcaaf4df6", value = "When the input is of type `radio` they can be grouped to gather with this identifier.")

  public String getGroupId() {
    return groupId;
  }


  public void setGroupId(String groupId) {
    
    
    
    this.groupId = groupId;
  }


  public TemplateSignerInputAllOf coordinates(TemplateSignerInputAllOfCoordinates coordinates) {
    
    
    
    
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateSignerInputAllOfCoordinates getCoordinates() {
    return coordinates;
  }


  public void setCoordinates(TemplateSignerInputAllOfCoordinates coordinates) {
    
    
    
    this.coordinates = coordinates;
  }


  public TemplateSignerInputAllOf dimensions(TemplateSignerInputAllOfDimensions dimensions) {
    
    
    
    
    this.dimensions = dimensions;
    return this;
  }

   /**
   * Get dimensions
   * @return dimensions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TemplateSignerInputAllOfDimensions getDimensions() {
    return dimensions;
  }


  public void setDimensions(TemplateSignerInputAllOfDimensions dimensions) {
    
    
    
    this.dimensions = dimensions;
  }


  public TemplateSignerInputAllOf label(String label) {
    
    
    
    
    this.label = label;
    return this;
  }

   /**
   * The label field is used especially for text, attachment, radio, and checkbox type inputs.
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Legal name", value = "The label field is used especially for text, attachment, radio, and checkbox type inputs.")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    
    
    
    this.label = label;
  }


  public TemplateSignerInputAllOf readOnly(Boolean readOnly) {
    
    
    
    
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Whether this input was defined as read-only(immutable by signers) or not
   * @return readOnly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Whether this input was defined as read-only(immutable by signers) or not")

  public Boolean getReadOnly() {
    return readOnly;
  }


  public void setReadOnly(Boolean readOnly) {
    
    
    
    this.readOnly = readOnly;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TemplateSignerInputAllOf instance itself
   */
  public TemplateSignerInputAllOf putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateSignerInputAllOf templateSignerInputAllOf = (TemplateSignerInputAllOf) o;
    return Objects.equals(this.type, templateSignerInputAllOf.type) &&
        Objects.equals(this.contentType, templateSignerInputAllOf.contentType) &&
        Objects.equals(this.isRequired, templateSignerInputAllOf.isRequired) &&
        Objects.equals(this.pageIndex, templateSignerInputAllOf.pageIndex) &&
        Objects.equals(this.documentId, templateSignerInputAllOf.documentId) &&
        Objects.equals(this.dropdownChoices, templateSignerInputAllOf.dropdownChoices) &&
        Objects.equals(this.groupId, templateSignerInputAllOf.groupId) &&
        Objects.equals(this.coordinates, templateSignerInputAllOf.coordinates) &&
        Objects.equals(this.dimensions, templateSignerInputAllOf.dimensions) &&
        Objects.equals(this.label, templateSignerInputAllOf.label) &&
        Objects.equals(this.readOnly, templateSignerInputAllOf.readOnly)&&
        Objects.equals(this.additionalProperties, templateSignerInputAllOf.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, contentType, isRequired, pageIndex, documentId, dropdownChoices, groupId, coordinates, dimensions, label, readOnly, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateSignerInputAllOf {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    dropdownChoices: ").append(toIndentedString(dropdownChoices)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("content_type");
    openapiFields.add("is_required");
    openapiFields.add("page_index");
    openapiFields.add("document_id");
    openapiFields.add("dropdown_choices");
    openapiFields.add("group_id");
    openapiFields.add("coordinates");
    openapiFields.add("dimensions");
    openapiFields.add("label");
    openapiFields.add("read_only");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TemplateSignerInputAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TemplateSignerInputAllOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateSignerInputAllOf is not found in the empty JSON string", TemplateSignerInputAllOf.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("content_type") != null && !jsonObj.get("content_type").isJsonNull()) && !jsonObj.get("content_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `content_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("content_type").toString()));
      }
      if (!jsonObj.get("document_id").isJsonNull() && (jsonObj.get("document_id") != null && !jsonObj.get("document_id").isJsonNull()) && !jsonObj.get("document_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `document_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("document_id").toString()));
      }
      // ensure the optional json data is an array if present (nullable)
      if (jsonObj.get("dropdown_choices") != null && !jsonObj.get("dropdown_choices").isJsonNull() && !jsonObj.get("dropdown_choices").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `dropdown_choices` to be an array in the JSON string or null but got `%s`", jsonObj.get("dropdown_choices").toString()));
      }
      if (!jsonObj.get("group_id").isJsonNull() && (jsonObj.get("group_id") != null && !jsonObj.get("group_id").isJsonNull()) && !jsonObj.get("group_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `group_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group_id").toString()));
      }
      // validate the optional field `coordinates`
      if (jsonObj.get("coordinates") != null && !jsonObj.get("coordinates").isJsonNull()) {
        TemplateSignerInputAllOfCoordinates.validateJsonObject(jsonObj.getAsJsonObject("coordinates"));
      }
      // validate the optional field `dimensions`
      if (jsonObj.get("dimensions") != null && !jsonObj.get("dimensions").isJsonNull()) {
        TemplateSignerInputAllOfDimensions.validateJsonObject(jsonObj.getAsJsonObject("dimensions"));
      }
      if (!jsonObj.get("label").isJsonNull() && (jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateSignerInputAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateSignerInputAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateSignerInputAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateSignerInputAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateSignerInputAllOf>() {
           @Override
           public void write(JsonWriter out, TemplateSignerInputAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateSignerInputAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TemplateSignerInputAllOf instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateSignerInputAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateSignerInputAllOf
  * @throws IOException if the JSON string is invalid with respect to TemplateSignerInputAllOf
  */
  public static TemplateSignerInputAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateSignerInputAllOf.class);
  }

 /**
  * Convert an instance of TemplateSignerInputAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

