/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Outcome;
import com.konfigthis.client.model.WorkflowsStartBasedOnRequestRequestFilesInner;
import com.konfigthis.client.model.WorkflowsStartBasedOnRequestRequestFlow;
import com.konfigthis.client.model.WorkflowsStartBasedOnRequestRequestFolder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * WorkflowsStartBasedOnRequestRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class WorkflowsStartBasedOnRequestRequest {
  /**
   * The type of the parameters object
   */
  @JsonAdapter(TypeEnum.Adapter.class)
 public enum TypeEnum {
    WORKFLOW_PARAMETERS("workflow_parameters");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_FLOW = "flow";
  @SerializedName(SERIALIZED_NAME_FLOW)
  private WorkflowsStartBasedOnRequestRequestFlow flow;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<WorkflowsStartBasedOnRequestRequestFilesInner> files = new ArrayList<>();

  public static final String SERIALIZED_NAME_FOLDER = "folder";
  @SerializedName(SERIALIZED_NAME_FOLDER)
  private WorkflowsStartBasedOnRequestRequestFolder folder;

  public static final String SERIALIZED_NAME_OUTCOMES = "outcomes";
  @SerializedName(SERIALIZED_NAME_OUTCOMES)
  private List<Outcome> outcomes = null;

  public WorkflowsStartBasedOnRequestRequest() {
  }

  public WorkflowsStartBasedOnRequestRequest type(TypeEnum type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * The type of the parameters object
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "WORKFLOW_PARAMETERS", value = "The type of the parameters object")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    
    
    
    this.type = type;
  }


  public WorkflowsStartBasedOnRequestRequest flow(WorkflowsStartBasedOnRequestRequestFlow flow) {
    
    
    
    
    this.flow = flow;
    return this;
  }

   /**
   * Get flow
   * @return flow
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public WorkflowsStartBasedOnRequestRequestFlow getFlow() {
    return flow;
  }


  public void setFlow(WorkflowsStartBasedOnRequestRequestFlow flow) {
    
    
    
    this.flow = flow;
  }


  public WorkflowsStartBasedOnRequestRequest files(List<WorkflowsStartBasedOnRequestRequestFilesInner> files) {
    
    
    
    
    this.files = files;
    return this;
  }

  public WorkflowsStartBasedOnRequestRequest addFilesItem(WorkflowsStartBasedOnRequestRequestFilesInner filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * The array of files for which the workflow should start. All files must be in the workflow&#39;s configured folder.
   * @return files
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The array of files for which the workflow should start. All files must be in the workflow's configured folder.")

  public List<WorkflowsStartBasedOnRequestRequestFilesInner> getFiles() {
    return files;
  }


  public void setFiles(List<WorkflowsStartBasedOnRequestRequestFilesInner> files) {
    
    
    
    this.files = files;
  }


  public WorkflowsStartBasedOnRequestRequest folder(WorkflowsStartBasedOnRequestRequestFolder folder) {
    
    
    
    
    this.folder = folder;
    return this;
  }

   /**
   * Get folder
   * @return folder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public WorkflowsStartBasedOnRequestRequestFolder getFolder() {
    return folder;
  }


  public void setFolder(WorkflowsStartBasedOnRequestRequestFolder folder) {
    
    
    
    this.folder = folder;
  }


  public WorkflowsStartBasedOnRequestRequest outcomes(List<Outcome> outcomes) {
    
    
    
    
    this.outcomes = outcomes;
    return this;
  }

  public WorkflowsStartBasedOnRequestRequest addOutcomesItem(Outcome outcomesItem) {
    if (this.outcomes == null) {
      this.outcomes = new ArrayList<>();
    }
    this.outcomes.add(outcomesItem);
    return this;
  }

   /**
   * A configurable outcome the workflow should complete.
   * @return outcomes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A configurable outcome the workflow should complete.")

  public List<Outcome> getOutcomes() {
    return outcomes;
  }


  public void setOutcomes(List<Outcome> outcomes) {
    
    
    
    this.outcomes = outcomes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WorkflowsStartBasedOnRequestRequest instance itself
   */
  public WorkflowsStartBasedOnRequestRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowsStartBasedOnRequestRequest workflowsStartBasedOnRequestRequest = (WorkflowsStartBasedOnRequestRequest) o;
    return Objects.equals(this.type, workflowsStartBasedOnRequestRequest.type) &&
        Objects.equals(this.flow, workflowsStartBasedOnRequestRequest.flow) &&
        Objects.equals(this.files, workflowsStartBasedOnRequestRequest.files) &&
        Objects.equals(this.folder, workflowsStartBasedOnRequestRequest.folder) &&
        Objects.equals(this.outcomes, workflowsStartBasedOnRequestRequest.outcomes)&&
        Objects.equals(this.additionalProperties, workflowsStartBasedOnRequestRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, flow, files, folder, outcomes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowsStartBasedOnRequestRequest {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    folder: ").append(toIndentedString(folder)).append("\n");
    sb.append("    outcomes: ").append(toIndentedString(outcomes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("flow");
    openapiFields.add("files");
    openapiFields.add("folder");
    openapiFields.add("outcomes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("flow");
    openapiRequiredFields.add("files");
    openapiRequiredFields.add("folder");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WorkflowsStartBasedOnRequestRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!WorkflowsStartBasedOnRequestRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowsStartBasedOnRequestRequest is not found in the empty JSON string", WorkflowsStartBasedOnRequestRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WorkflowsStartBasedOnRequestRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `flow`
      WorkflowsStartBasedOnRequestRequestFlow.validateJsonObject(jsonObj.getAsJsonObject("flow"));
      // ensure the json data is an array
      if (!jsonObj.get("files").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
      }

      JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
      // validate the required field `files` (array)
      for (int i = 0; i < jsonArrayfiles.size(); i++) {
        WorkflowsStartBasedOnRequestRequestFilesInner.validateJsonObject(jsonArrayfiles.get(i).getAsJsonObject());
      };
      // validate the required field `folder`
      WorkflowsStartBasedOnRequestRequestFolder.validateJsonObject(jsonObj.getAsJsonObject("folder"));
      if (jsonObj.get("outcomes") != null && !jsonObj.get("outcomes").isJsonNull()) {
        JsonArray jsonArrayoutcomes = jsonObj.getAsJsonArray("outcomes");
        if (jsonArrayoutcomes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("outcomes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `outcomes` to be an array in the JSON string but got `%s`", jsonObj.get("outcomes").toString()));
          }

          // validate the optional field `outcomes` (array)
          for (int i = 0; i < jsonArrayoutcomes.size(); i++) {
            Outcome.validateJsonObject(jsonArrayoutcomes.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowsStartBasedOnRequestRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowsStartBasedOnRequestRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowsStartBasedOnRequestRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowsStartBasedOnRequestRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowsStartBasedOnRequestRequest>() {
           @Override
           public void write(JsonWriter out, WorkflowsStartBasedOnRequestRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowsStartBasedOnRequestRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             WorkflowsStartBasedOnRequestRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowsStartBasedOnRequestRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowsStartBasedOnRequestRequest
  * @throws IOException if the JSON string is invalid with respect to WorkflowsStartBasedOnRequestRequest
  */
  public static WorkflowsStartBasedOnRequestRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowsStartBasedOnRequestRequest.class);
  }

 /**
  * Convert an instance of WorkflowsStartBasedOnRequestRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

