/*
 * Box Platform API
 * [Box Platform](https://box.dev) provides functionality to provide access to content stored within [Box](https://box.com). It provides endpoints for basic manipulation of files and folders, management of users within an enterprise, as well as more complex topics such as legal holds and retention policies.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: devrel@box.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ClientError;
import com.konfigthis.client.model.StandardAndZonesStoragePolicyAssignmentsCreateAssignmentRequest;
import com.konfigthis.client.model.StandardAndZonesStoragePolicyAssignmentsCreateAssignmentRequestAssignedTo;
import com.konfigthis.client.model.StandardAndZonesStoragePolicyAssignmentsCreateAssignmentRequestStoragePolicy;
import com.konfigthis.client.model.StandardAndZonesStoragePolicyAssignmentsUpdateSpecificAssignmentRequest;
import com.konfigthis.client.model.StandardAndZonesStoragePolicyAssignmentsUpdateSpecificAssignmentRequestStoragePolicy;
import com.konfigthis.client.model.StoragePolicyAssignment;
import com.konfigthis.client.model.StoragePolicyAssignments;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StandardAndZonesStoragePolicyAssignmentsApi
 */
@Disabled
public class StandardAndZonesStoragePolicyAssignmentsApiTest {

    private static StandardAndZonesStoragePolicyAssignmentsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new StandardAndZonesStoragePolicyAssignmentsApi(apiClient);
    }

    /**
     * Assign storage policy
     *
     * Creates a storage policy assignment for an enterprise or user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createAssignmentTest() throws ApiException {
        StandardAndZonesStoragePolicyAssignmentsCreateAssignmentRequestStoragePolicy storagePolicy = null;
        StandardAndZonesStoragePolicyAssignmentsCreateAssignmentRequestAssignedTo assignedTo = null;
        StoragePolicyAssignment response = api.createAssignment(storagePolicy, assignedTo)
                .execute();
        // TODO: test validations
    }

    /**
     * Get storage policy assignment
     *
     * Fetches a specific storage policy assignment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpecificAssignmentTest() throws ApiException {
        String storagePolicyAssignmentId = null;
        StoragePolicyAssignment response = api.getSpecificAssignment(storagePolicyAssignmentId)
                .execute();
        // TODO: test validations
    }

    /**
     * List storage policy assignments
     *
     * Fetches all the storage policy assignment for an enterprise or user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAssignmentsTest() throws ApiException {
        String resolvedForType = null;
        String resolvedForId = null;
        String marker = null;
        StoragePolicyAssignments response = api.listAssignments(resolvedForType, resolvedForId)
                .marker(marker)
                .execute();
        // TODO: test validations
    }

    /**
     * Unassign storage policy
     *
     * Delete a storage policy assignment.  Deleting a storage policy assignment on a user will have the user inherit the enterprise&#39;s default storage policy.  There is a rate limit for calling this endpoint of only twice per user in a 24 hour time frame.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unassignStoragePolicyTest() throws ApiException {
        String storagePolicyAssignmentId = null;
        api.unassignStoragePolicy(storagePolicyAssignmentId)
                .execute();
        // TODO: test validations
    }

    /**
     * Update storage policy assignment
     *
     * Updates a specific storage policy assignment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSpecificAssignmentTest() throws ApiException {
        StandardAndZonesStoragePolicyAssignmentsUpdateSpecificAssignmentRequestStoragePolicy storagePolicy = null;
        String storagePolicyAssignmentId = null;
        StoragePolicyAssignment response = api.updateSpecificAssignment(storagePolicy, storagePolicyAssignmentId)
                .execute();
        // TODO: test validations
    }

}
